# Generated by Django 2.2.3 on 2019-11-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamics',
            options={'verbose_name': '动态', 'verbose_name_plural': '动态'},
        ),
        migrations.AlterModelOptions(
            name='gone',
            options={'verbose_name': '去过', 'verbose_name_plural': '去过'},
        ),
        migrations.AlterField(
            model_name='dynamics',
            name='text',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
