# Generated by Django 2.2.5 on 2019-11-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191126_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
