# Generated by Django 2.2.5 on 2019-11-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicsPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=128, null=True)),
                ('dynamics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Dynamics')),
            ],
            options={
                'verbose_name': '动态图片',
                'verbose_name_plural': '动态图片',
            },
        ),
    ]
