# Generated by Django 2.2.5 on 2019-11-28 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_dynamics_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamics',
            name='time',
            field=models.CharField(default=datetime.datetime.now, max_length=50),
        ),
    ]
