# Generated by Django 2.2.5 on 2019-11-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191129_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamics',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dynamics',
            name='time',
            field=models.CharField(default=1575027194, max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField()),
                ('time', models.CharField(default=1575027194, max_length=50)),
                ('dynamics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Dynamics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '动态评论',
                'verbose_name_plural': '动态评论',
            },
        ),
    ]
