# Generated by Django 2.2.5 on 2019-12-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191129_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default=1576052059, max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamics',
            name='time',
            field=models.CharField(default=1576052059, max_length=50),
        ),
    ]
