# Generated by Django 2.2.5 on 2019-12-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191211_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamics',
            name='like',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default=1576341574, max_length=50),
        ),
        migrations.AlterField(
            model_name='dynamics',
            name='time',
            field=models.CharField(default=1576341574, max_length=50),
        ),
        migrations.CreateModel(
            name='DynamicsLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dynamics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Dynamics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
            },
        ),
    ]
