# Generated by Django 2.2.7 on 2020-02-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200201_1456'),
        ('user', '0013_auto_20200201_1504'),
    ]

    operations = [
    ]
