# Generated by Django 2.2.3 on 2019-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0002_auto_20191126_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
