# Generated by Django 2.2.3 on 2019-11-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0003_auto_20191126_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
