# Generated by Django 2.2.3 on 2019-11-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0004_auto_20191126_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='poem_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
