# Generated by Django 2.2.5 on 2019-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0007_auto_20191126_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='name_ch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
