# Generated by Django 2.2.5 on 2019-12-11 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0008_province_name_ch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('answer', models.CharField(blank=True, max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.Province')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
