# Generated by Django 2.2.5 on 2019-12-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0009_test'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='test',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='option_A',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_B',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_C',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_D',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
