# Generated by Django 2.2.7 on 2020-02-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0010_auto_20191211_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='author',
        ),
        migrations.RemoveField(
            model_name='province',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='province',
            name='poem_content',
        ),
        migrations.RemoveField(
            model_name='province',
            name='poem_name',
        ),
        migrations.RemoveField(
            model_name='province',
            name='translation',
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_name', models.CharField(blank=True, max_length=40, null=True)),
                ('poem_content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('translation', models.TextField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.Province')),
            ],
            options={
                'verbose_name': '唐诗',
                'verbose_name_plural': '唐诗',
            },
        ),
    ]
